### ISSUE TITLE
Form group margin bottom

### ISSUE THREAD

**Issue by FredericEspiau** [ovh-ux/ovh-ui-kit-bs#46]
https://github.com/ovh-ux/ovh-ui-kit-bs/blob/edb2484f4601aa6b044bc458469e81b25d98404d/src/bootstrap/_variables.less#L219

The margin-bottom should be `20px` just like `oui-field`'s margin-bottom

**Comment by AxelPeter** [comment]
This issue has been fixed with https://github.com/ovh-ux/ovh-ui-kit-bs/releases/tag/v1.1.2
